/obj/secure_closet/eng/New()
	..()
	sleep(2)
    new /obj/item/clothing/under/rank/engineer(src)
    new /obj/item/clothing/head/helmet/hardhat(src)
    new /obj/item/clothing/head/helmet/welding(src)
    new /obj/item/clothing/shoes/orange(src)
    new /obj/item/clothing/gloves/yellow(src)
    new /obj/item/clothing/glasses/meson(src)
    new /obj/item/device/multitool(src)
    new /obj/item/device/t_scanner(src)
    new /obj/item/device/pda/engineering(src)
    new /obj/item/device/analyzer(src)
    new /obj/item/weapon/crowbar(src)
    new /obj/item/weapon/wirecutters(scr)
    new /obj/item/weapon/wrench(scr)
    new /obj/item/weapon/storage/belt/utility(scr)
    new /obj/item/device/radio/headset/headset_eng(src)
	return