/obj/secure_closet/eng/New()
	..()
	sleep(2)
	new /obj/item/clothing/under/rank/engineer(src)
	new /obj/item/clothing/head/helmet/hardhat(src)
	new /obj/item/clothing/head/helmet/welding(src)
	new /obj/item/clothing/shoes/orange(src)
	new /obj/item/clothing/gloves/yellow(src)
	new /obj/item/clothing/glasses/meson(src)
	new /obj/item/weapon/storage/belt/utility(src)
	new /obj/item/device/radio/headset/headset_eng(src)
	new /obj/item/device/pda/engineering(src)
	new /obj/item/clothing/shoes/magnetic(src)
	new /obj/item/weapon/storage/backpack/industrial(src)
	new /obj/item/clothing/suit/storage/hazard(src)
	return

/obj/secure_closet/ce/New()
	..()
	sleep(2)
	new /obj/item/clothing/under/rank/chief_engineer(src)
	new /obj/item/clothing/head/helmet/hardhat(src)
	new /obj/item/clothing/shoes/brown(src)
	new /obj/item/clothing/gloves/yellow(src)
	new /obj/item/clothing/glasses/meson(src)
	new /obj/item/device/pda/heads/ce(src)
	new /obj/item/weapon/storage/belt/utility(src)
	new /obj/item/device/radio/headset/heads/ce(src)
	new /obj/item/weapon/storage/backpack/industrial(src)
	new /obj/item/clothing/suit/storage/hazard(src)
	return

/obj/secure_closet/engelec/New()
	..()
	sleep(2)
	new /obj/item/weapon/storage/toolbox/electrical(src)
	new /obj/item/weapon/storage/toolbox/electrical(src)
	new /obj/item/device/multitool(src)
	new /obj/item/device/multitool(src)
	new /obj/item/device/multitool(src)
	new /obj/item/device/t_scanner(src)
	new /obj/item/device/t_scanner(src)
	new /obj/item/device/t_scanner(src)
	new /obj/item/weapon/CableCoil/power(src)
	new /obj/item/weapon/CableCoil/power(src)
	new /obj/item/weapon/CableCoil/power(src)
	new /obj/item/weapon/CableCoil/power(src)
	return

/obj/secure_closet/engweld/New()
	..()
	sleep(2)
	new /obj/item/weapon/weldingtool(src)
	new /obj/item/weapon/weldingtool(src)
	new /obj/item/weapon/weldingtool(src)
	new /obj/item/weapon/weldingtool(src)
	new /obj/item/clothing/head/helmet/welding(src)
	new /obj/item/clothing/head/helmet/welding(src)
	new /obj/item/clothing/head/helmet/welding(src)
	new /obj/item/clothing/head/helmet/welding(src)
	return

