/obj/secure_closet/medical1/New()
	..()
	sleep(2)
	new /obj/item/weapon/storage/gl_kit( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/antitoxin( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/antitoxin( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/antitoxin( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/inaprovaline( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/inaprovaline( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/inaprovaline( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/stoxin( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/stoxin( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/toxin( src )
	new /obj/item/weapon/storage/firstaid/syringes( src )
	new /obj/item/weapon/reagent_containers/dropper( src )
	new /obj/item/weapon/reagent_containers/dropper( src )
	new /obj/item/weapon/reagent_containers/glass/beaker( src )
	new /obj/item/weapon/reagent_containers/glass/beaker( src )
	return
/obj/secure_closet/medical3/New()
	..()
	sleep(2)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/A(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/B(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/O(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/AB(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/A(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/B(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/O(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/AB(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/A(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/B(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/O(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/AB(src)
	return
/obj/secure_closet/medical2/New()
	..()
	sleep(2)
	new /obj/item/weapon/tank/anesthetic( src )
	new /obj/item/weapon/tank/anesthetic( src )
	new /obj/item/weapon/tank/anesthetic( src )
	new /obj/item/weapon/tank/anesthetic( src )
	new /obj/item/weapon/tank/anesthetic( src )
	new /obj/item/clothing/mask/medical( src )
	new /obj/item/clothing/mask/medical( src )
	new /obj/item/clothing/mask/medical( src )
	new /obj/item/clothing/mask/medical( src )
	return
/obj/secure_closet/medicalcloset/New()
	..()
	sleep(2)
	new /obj/item/device/pda/medical(src)
	new /obj/item/clothing/under/rank/medical( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/weapon/storage/stma_kit( src )
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/device/radio/headset/headset_med(src)
	new /obj/item/clothing/gloves/latex(src)
	new /obj/item/weapon/storage/belt/medical(src)
	new /obj/item/weapon/storage/backpack/medic(src)
	return

/obj/secure_closet/hydro/New()
	..()
	sleep(2)
	new /obj/item/device/pda/hydro(src)
	new /obj/item/clothing/under/rank/hydroponics(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/gloves/black(src)
	new /obj/item/weapon/storage/backpack(src)
	new /obj/item/device/radio/headset(src)
	new /obj/item/clothing/head/green_band(src)
	new /obj/item/clothing/suit/storage/apron(src)
	return

/obj/secure_closet/robot/New()
	..()
	sleep(2)
	new /obj/item/device/pda/robot(src)
	new /obj/item/clothing/under/rank/roboticist( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/weapon/storage/stma_kit( src )
	new /obj/item/weapon/storage/lglo_kit( src )
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/device/radio/headset/headset_medsci(src)
	new /obj/item/clothing/gloves/latex(src)
	new /obj/item/weapon/storage/backpack/medic(src)
	return

/obj/secure_closet/genetics/New()
    ..()
    sleep(2)
    new /obj/item/device/pda/gene(src)
    new /obj/item/clothing/under/rank/geneticist( src )
    new /obj/item/clothing/shoes/white( src )
    new /obj/item/weapon/storage/stma_kit( src )
    new /obj/item/clothing/suit/storage/labcoat/gen(src)
    new /obj/item/device/radio/headset/headset_medsci(src)
    new /obj/item/clothing/gloves/latex(src)
    new /obj/item/weapon/storage/belt/medical(src)
    new /obj/item/weapon/storage/backpack/medic(src)
    return