/obj/secure_closet/security1/New()
	..()
	sleep(2)
	new /obj/item/device/radio/headset/headset_sec(src)
	new /obj/item/weapon/handcuffs(src)
	new /obj/item/weapon/gun/energy/taser_gun(src)
	new /obj/item/clothing/under/color/red(src)
	new /obj/item/clothing/suit/armor/vest(src)
	new /obj/item/clothing/suit/storage/gearharness(src)
	new /obj/item/clothing/gloves/red(src)
	new /obj/item/clothing/shoes/brown(src)
	new /obj/item/clothing/head/helmet(src)
	new /obj/item/clothing/glasses/sunglasses(src)
	new /obj/item/weapon/baton(src)
	new /obj/item/device/flash(src)
	new /obj/item/weapon/storage/flashbang_kit(src)
	new /obj/item/clothing/head/helmet/Secsoft(src)
	return

/obj/secure_closet/security2/New()
	..()
	sleep(2)
	new /obj/item/device/radio/headset/headset_sec(src)
	new /obj/item/clothing/under/det( src )
	new /obj/item/clothing/under/ftech( src )
	new /obj/item/clothing/suit/storage/det_suit( src )
	new /obj/item/clothing/suit/storage/gearharness(src)
	new /obj/item/clothing/gloves/black( src )
	new /obj/item/clothing/gloves/black( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/head/det_hat( src )
	new /obj/item/weapon/storage/fcard_kit( src )
	new /obj/item/weapon/storage/fcard_kit( src )
	new /obj/item/weapon/storage/fcard_kit( src )
	new /obj/item/weapon/storage/lglo_kit( src )
	new /obj/item/weapon/fcardholder( src )
	new /obj/item/weapon/fcardholder( src )
	new /obj/item/weapon/fcardholder( src )
	new /obj/item/weapon/fcardholder( src )
	new /obj/item/device/detective_scanner( src )
	new /obj/item/device/detective_scanner( src )
	new /obj/item/device/detective_scanner( src )
	new /obj/item/weapon/storage/box/evidence( src )
	return

/obj/secure_closet/highsec/New() // HoP closet
	..()
	sleep(2)
	new/obj/item/device/radio/headset/heads/hop(src)
	new /obj/item/weapon/gun/energy/general( src )
	new /obj/item/device/flash( src )
	new /obj/item/weapon/storage/id_kit( src )
	new /obj/item/clothing/under/rank/head_of_personnel( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/glasses/sunglasses( src )
	new /obj/item/clothing/suit/armor/vest( src )
	new /obj/item/clothing/head/helmet( src )
	return

/obj/secure_closet/hos/New()
	..()
	sleep(2)
	new/obj/item/device/radio/headset/heads/hos(src)
	new /obj/item/weapon/gun/energy/general( src )
	new /obj/item/device/flash( src )
	new /obj/item/weapon/storage/id_kit( src )
	new /obj/item/clothing/under/rank/head_of_security( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/glasses/sunglasses( src )
	new /obj/item/clothing/suit/hos( src )
	new /obj/item/clothing/head/helmet/HoS(src)
	new /obj/item/weapon/storage/id_kit( src )
	new /obj/item/weapon/storage/flashbang_kit(src)
	new /obj/item/weapon/handcuffs(src)
	new /obj/item/weapon/baton(src)
	new /obj/item/clothing/gloves/red(src)
	return

/obj/secure_closet/warden/New()
	..()
	sleep(2)
	new/obj/item/device/radio/headset/heads/hos(src)
	new /obj/item/weapon/gun/energy/general( src )
	new /obj/item/device/flash( src )
	new /obj/item/clothing/under/rank/warden( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/glasses/sunglasses( src )
	new /obj/item/clothing/suit/warden_jacket( src )
	new /obj/item/clothing/head/helmet/wardencap(src)
	new /obj/item/weapon/storage/handcuff_kit(src)
	new /obj/item/weapon/handcuffs(src)
	new /obj/item/weapon/baton(src)
	new /obj/item/clothing/gloves/black(src)
	return



//Added by Strumpetplaya - Research Director's Closet for office.
/obj/secure_closet/rd/New()
	..()
	sleep(2)
	new /obj/item/device/radio/headset/heads/rd( src )
	new /obj/item/clothing/under/rank/research_director( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/glasses/regular( src )
	new /obj/item/clothing/suit/storage/labcoat( src )
	return
/obj/secure_closet/qm/New()
	..()
	sleep(2)
	new /obj/item/clothing/under/cargo ( src )
	new /obj/item/clothing/gloves/black ( src )
	new /obj/item/weapon/hand_labeler ( src )
	new /obj/item/device/radio/headset/headset_cargo(src)
	new /obj/item/clothing/glasses/sunglasses(src)
	new /obj/item/clothing/head/helmet/cargosoft(src)
	return