/obj/closet/l3closet/New()
	..()
	sleep(2)
	new /obj/item/clothing/suit/bio_suit( src )
	new /obj/item/clothing/under/color/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/head/bio_hood( src )
	new /obj/item/clothing/gloves/latex( src )

/obj/closet/l3jancloset/New()
	..()
	sleep(2)
	new /obj/item/clothing/head/bio_hood/janitor( src )
	new /obj/item/clothing/suit/bio_suit/janitor( src )
	new /obj/item/clothing/gloves/latex( src )

/obj/closet/l3scicloset/New()
    ..()
    sleep(2)
    new /obj/item/clothing/suit/bio_suit/yellow(src)
    new /obj/item/clothing/head/bio_hood/yellow(src)
    new /obj/item/clothing/gloves/latex( src )
    new /obj/item/clothing/shoes/orange( src )
    new /obj/item/clothing/under/color/white( src )

/obj/closet/l3seccloset/New()
    ..()
    sleep(2)
    new /obj/item/clothing/head/bio_hood/fred(src)
    new /obj/item/clothing/suit/bio_suit/fred(src)
    new /obj/item/clothing/gloves/latex( src )
    new /obj/item/clothing/shoes/orange( src )
    new /obj/item/clothing/under/color/white( src )