/obj/structure/closet/wardrobe/regular/New()
	..()
	new /obj/item/clothing/under/color/blue( src )
	new /obj/item/clothing/under/color/blue( src )
	new /obj/item/clothing/under/color/blue( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	return

/obj/structure/closet/wardrobe/red/New()
	..()
	new /obj/item/clothing/under/color/red( src )
	new /obj/item/clothing/under/color/red( src )
	new /obj/item/clothing/under/color/red( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	return
/obj/structure/closet/wardrobe/forensics_red/New()
	..()
	new /obj/item/clothing/under/rank/forensic_technician( src )
	new /obj/item/clothing/under/rank/forensic_technician( src )
	new /obj/item/clothing/under/rank/forensic_technician( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	return

/obj/structure/closet/wardrobe/pink/New()
	..()
	new /obj/item/clothing/under/color/pink( src )
	new /obj/item/clothing/under/color/pink( src )
	new /obj/item/clothing/under/color/pink( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	return

/obj/structure/closet/wardrobe/black/New()
	..()
	new /obj/item/clothing/under/color/black( src )
	new /obj/item/clothing/under/color/black( src )
	new /obj/item/clothing/under/color/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	return

/obj/structure/closet/wardrobe/chaplain_black/New()
	..()
	new /obj/item/clothing/under/rank/chaplain( src )
	new /obj/item/clothing/under/rank/chaplain( src )
	new /obj/item/clothing/under/rank/chaplain( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	return

/obj/structure/closet/wardrobe/green/New()
	..()
	new /obj/item/clothing/under/color/green( src )
	new /obj/item/clothing/under/color/green( src )
	new /obj/item/clothing/under/color/green( src )
	new /obj/item/clothing/shoes/green( src )
	new /obj/item/clothing/shoes/green( src )
	new /obj/item/clothing/shoes/green( src )
	return

/obj/structure/closet/wardrobe/orange/New()
	..()
	new /obj/item/clothing/under/color/orange( src )
	new /obj/item/clothing/under/color/orange( src )
	new /obj/item/clothing/under/color/orange( src )
	new /obj/item/clothing/shoes/orange( src )
	new /obj/item/clothing/shoes/orange( src )
	new /obj/item/clothing/shoes/orange( src )
	return

/obj/structure/closet/wardrobe/yellow/New()
	..()
	new /obj/item/clothing/under/color/yellow( src )
	new /obj/item/clothing/under/color/yellow( src )
	new /obj/item/clothing/under/color/yellow( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	return

/obj/structure/closet/wardrobe/atmospherics_yellow/New()
	..()
	new /obj/item/clothing/under/rank/atmospheric_technician(src)
	new /obj/item/clothing/under/rank/atmospheric_technician(src)
	new /obj/item/clothing/under/rank/atmospheric_technician(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/device/radio/headset/headset_eng(src)
	new /obj/item/device/radio/headset/headset_eng(src)
	new /obj/item/device/radio/headset/headset_eng(src)
	return

/obj/structure/closet/wardrobe/engineering_yellow/New()
	..()
	new /obj/item/clothing/under/rank/engineer(src)
	new /obj/item/clothing/under/rank/engineer(src)
	new /obj/item/clothing/under/rank/engineer(src)
	new /obj/item/clothing/under/rank/engineer(src)
	new /obj/item/clothing/shoes/orange(src)
	new /obj/item/clothing/shoes/orange(src)
	new /obj/item/clothing/shoes/orange(src)
	new /obj/item/clothing/shoes/orange(src)
	new /obj/item/device/radio/headset/headset_eng(src)
	new /obj/item/device/radio/headset/headset_eng(src)
	new /obj/item/device/radio/headset/headset_eng(src)
	new /obj/item/device/radio/headset/headset_eng(src)
	return

/obj/structure/closet/wardrobe/quartermasters/New()
	..()
	new /obj/item/clothing/under/rank/cargotech ( src )
	new /obj/item/clothing/under/rank/cargotech ( src )
	new /obj/item/clothing/under/rank/cargotech ( src )
	new /obj/item/clothing/under/rank/cargotech ( src )
	new /obj/item/clothing/gloves/black ( src )
	new /obj/item/clothing/gloves/black ( src )
	new /obj/item/clothing/gloves/black ( src )
	new /obj/item/clothing/gloves/black ( src )
	new /obj/item/weapon/hand_labeler ( src )
	new /obj/item/clothing/shoes/black ( src )
	new /obj/item/clothing/shoes/black ( src )
	new /obj/item/clothing/shoes/black ( src )
	new /obj/item/clothing/shoes/black ( src )
	return

/obj/structure/closet/wardrobe/white/New() // Medical wardrobe
	..()
	new /obj/item/clothing/under/rank/medical( src )
	new /obj/item/clothing/under/rank/medical( src )
	new /obj/item/clothing/under/rank/medical( src )
	new /obj/item/clothing/under/rank/medical( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/weapon/storage/box/stma( src )
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/device/radio/headset/headset_med(src)
	new /obj/item/device/radio/headset/headset_med(src)
	new /obj/item/device/radio/headset/headset_med(src)
	new /obj/item/device/radio/headset/headset_med(src)
	return

/obj/structure/closet/wardrobe/chemistry_white/New()
	..()
	new /obj/item/clothing/under/rank/chemist( src )
	new /obj/item/clothing/under/rank/chemist( src )
	new /obj/item/clothing/under/rank/chemist( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/weapon/storage/box/stma( src )
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/device/radio/headset/headset_medsci(src)
	new /obj/item/device/radio/headset/headset_medsci(src)
	new /obj/item/device/radio/headset/headset_medsci(src)
	return

/obj/structure/closet/wardrobe/toxins_white/New()
	..()
	new /obj/item/clothing/under/rank/scientist( src )
	new /obj/item/clothing/under/rank/scientist( src )
	new /obj/item/clothing/under/rank/scientist( src )
	new /obj/item/clothing/under/rank/scientist( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/weapon/storage/box/stma( src )
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/device/radio/headset/headset_sci(src)
	new /obj/item/device/radio/headset/headset_sci(src)
	new /obj/item/device/radio/headset/headset_sci(src)
	return

/obj/structure/closet/wardrobe/robotics_white/New()
	..()
	new /obj/item/clothing/under/rank/roboticist( src )
	new /obj/item/clothing/under/rank/roboticist( src )
	new /obj/item/clothing/under/rank/roboticist( src )
	new /obj/item/clothing/under/rank/roboticist( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/weapon/storage/box/stma( src )
	new /obj/item/weapon/storage/box/lglo( src )
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/device/radio/headset/headset_medsci(src)
	new /obj/item/device/radio/headset/headset_medsci(src)
	return

/obj/structure/closet/wardrobe/genetics_white/New()
	..()
	new /obj/item/clothing/under/rank/geneticist( src )
	new /obj/item/clothing/under/rank/geneticist( src )
	new /obj/item/clothing/under/rank/geneticist( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/clothing/shoes/white( src )
	new /obj/item/weapon/storage/box/stma( src )
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/clothing/suit/storage/labcoat(src)
	new /obj/item/device/radio/headset/headset_medsci(src)
	new /obj/item/device/radio/headset/headset_medsci(src)
	new /obj/item/device/radio/headset/headset_medsci(src)
	return

/obj/structure/closet/wardrobe/grey/New()
	..()
	new /obj/item/clothing/under/color/grey( src )
	new /obj/item/clothing/under/color/grey( src )
	new /obj/item/clothing/under/color/grey( src )
	new /obj/item/clothing/under/color/grey( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	return

/obj/structure/closet/wardrobe/mixed/New()
	..()
	new /obj/item/clothing/under/color/blue( src )
	new /obj/item/clothing/under/color/blue( src )
	new /obj/item/clothing/under/color/pink( src )
	new /obj/item/clothing/under/color/pink( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/shoes/brown( src )
	return

/obj/structure/closet/wardrobe/bar/New()
	..()
	new /obj/item/clothing/under/rank/bartender( src )
	new /obj/item/clothing/under/rank/bartender( src )
	new /obj/item/clothing/head/that( src )
	new /obj/item/clothing/head/that( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/device/pda/bar( src )
	new /obj/item/device/pda/bar( src )
	return

/obj/structure/closet/lawcloset/New()
	..()
	new /obj/item/clothing/under/lawyer/black( src )
	new /obj/item/clothing/under/lawyer/red ( src )
	new /obj/item/clothing/under/lawyer/blue ( src )
	new /obj/item/clothing/shoes/brown(src)
	new /obj/item/clothing/shoes/brown(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/weapon/storage/briefcase(src)
	new /obj/item/weapon/storage/briefcase(src)
	return

/obj/structure/closet/wardrobe/hydroponics/New()
	..()
	new /obj/item/clothing/under/rank/hydroponics( src )
	new /obj/item/clothing/under/rank/hydroponics( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/clothing/shoes/black( src )
	new /obj/item/weapon/storage/box/lglo( src )
	return

/obj/structure/closet/toolcloset/New() //¡Î‡‰, Ú˚ Õ¿’”ﬂ ¬Ã≈—“Œ “¿¡Œ¬ “”“ œ–Œ¡≈À€ ﬁ«¿À, ”≈¡¿Õ —–¿Õ€…?
	..()
	new /obj/item/weapon/storage/toolbox/mechanical(src)
	new /obj/item/weapon/wrench(src)
	new /obj/item/weapon/wirecutters(src)
	new /obj/item/weapon/screwdriver(src)
	new /obj/item/device/flashlight(src)
	if(prob(20)) new /obj/item/device/multitool(src)
	if(prob(5)) new /obj/item/clothing/gloves/yellow(src)
	if(prob(20)) new /obj/item/weapon/storage/belt/utility(src)
	return